[package]
name = "Compilador_Rust"
version = "0.1.0"
edition = "2021"
default-run = "main"

[dependencies]
regex = "1.11.0"

[[bin]]
name = "tokenize"
path = "src/tokenize.rs"

[[bin]]
name = "tokens"
path = "src/tokens.rs"

[[bin]]
name = "main"
path = "src/main.rs"